# Generated by Django 4.2.27 on 2026-01-19 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='When this reporting relationship began')),
                ('end_date', models.DateField(blank=True, help_text='When this reporting relationship ended (NULL = currently active)', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Quick filter for current relationships')),
                ('notes', models.TextField(blank=True, help_text='Optional context about this relationship')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(help_text='The user who reports to a manager', on_delete=django.db.models.deletion.PROTECT, related_name='reporting_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this relationship', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reporting_lines', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(help_text='The user who manages the consultant', on_delete=django.db.models.deletion.PROTECT, related_name='managing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hierarchy_reporting_line',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['consultant', 'is_active'], name='hierarchy_r_consult_245278_idx'), models.Index(fields=['manager', 'is_active'], name='hierarchy_r_manager_afdf4d_idx'), models.Index(fields=['start_date', 'end_date'], name='hierarchy_r_start_d_7e7086_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='reportingline',
            constraint=models.CheckConstraint(check=models.Q(('consultant', models.F('manager')), _negated=True), name='no_self_management'),
        ),
        migrations.AddConstraint(
            model_name='reportingline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('consultant',), name='one_active_manager_per_consultant'),
        ),
        migrations.AddConstraint(
            model_name='reportingline',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='end_date_after_start_date'),
        ),
    ]
