# Generated by Django 4.2.27 on 2026-01-19 23:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('ACH', 'ACH/Direct Deposit'), ('WIRE', 'Wire Transfer'), ('CHECK', 'Paper Check'), ('INTERNATIONAL', 'International Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('INACTIVE', 'Inactive')], default='PENDING', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('routing_number', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'Must be 9 digits')])),
                ('account_number', models.CharField(max_length=17)),
                ('account_type', models.CharField(choices=[('CHECKING', 'Checking Account'), ('SAVINGS', 'Savings Account')], max_length=20)),
                ('swift_code', models.CharField(blank=True, max_length=11, null=True)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_paymentmethod',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('processor_type', models.CharField(choices=[('MANUAL', 'Manual Confirmation'), ('ACH', 'ACH Processor'), ('WIRE', 'Wire Transfer'), ('STRIPE', 'Stripe'), ('WISE', 'Wise')], default='MANUAL', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('confirmation_code', models.CharField(blank=True, max_length=100)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transaction', to='payouts.payoutbatch')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_transactions', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_transactions', to=settings.AUTH_USER_MODEL)),
                ('parent_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='payments.paymenttransaction')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.paymentmethod')),
            ],
            options={
                'db_table': 'payments_paymenttransaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Reconciliation'), ('RECONCILED', 'Reconciled (No Issues)'), ('DISCREPANCY', 'Discrepancy Found')], max_length=20)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discrepancy_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discrepancy_reason', models.TextField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='payouts.payoutbatch')),
                ('reconciled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations', to='payments.paymenttransaction')),
            ],
            options={
                'db_table': 'payments_paymentreconciliation',
                'ordering': ['-reconciliation_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('PAYMENT_METHOD_CREATED', 'Payment Method Created'), ('PAYMENT_METHOD_VERIFIED', 'Payment Method Verified'), ('PAYMENT_METHOD_INACTIVATED', 'Payment Method Inactivated'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_CANCELLED', 'Payment Cancelled'), ('W9_SUBMITTED', 'W-9 Submitted'), ('W9_APPROVED', 'W-9 Approved'), ('W9_REJECTED', 'W-9 Rejected'), ('TAX_DOCUMENT_GENERATED', '1099 Generated'), ('TAX_DOCUMENT_SENT', '1099 Sent to Consultant'), ('TAX_DOCUMENT_FILED', '1099 Filed with IRS'), ('RECONCILIATION_COMPLETED', 'Reconciliation Completed')], max_length=50)),
                ('target_model', models.CharField(max_length=50)),
                ('target_id', models.IntegerField()),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_paymentauditlog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='W9Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('legal_name', models.CharField(max_length=255)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('entity_type', models.CharField(choices=[('INDIVIDUAL', 'Individual/Sole Proprietor'), ('LLC', 'Limited Liability Company'), ('C_CORP', 'C Corporation'), ('S_CORP', 'S Corporation'), ('PARTNERSHIP', 'Partnership'), ('TRUST', 'Trust/Estate')], max_length=50)),
                ('tax_classification', models.CharField(blank=True, choices=[('C', 'C Corporation'), ('S', 'S Corporation'), ('P', 'Partnership')], max_length=50)),
                ('tin_type', models.CharField(choices=[('SSN', 'Social Security Number'), ('EIN', 'Employer Identification Number')], max_length=10)),
                ('tin', models.CharField(max_length=11, unique=True)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(default='US', max_length=2)),
                ('exempt_from_backup_withholding', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='w9_information', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_w9s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'W-9 Information',
                'verbose_name_plural': 'W-9 Information',
                'db_table': 'payments_w9information',
                'indexes': [models.Index(fields=['status'], name='payments_w9_status_2040d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaxDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.IntegerField()),
                ('document_type', models.CharField(choices=[('1099-NEC', '1099-NEC (Nonemployee Compensation)'), ('1099-C', '1099-C (Corrected)')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('file_path', models.CharField(max_length=500)),
                ('file_hash', models.CharField(max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sent_to_consultant', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('filed_with_irs', models.BooleanField(default=False)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_documents', to=settings.AUTH_USER_MODEL)),
                ('corrects_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='payments.taxdocument')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tax_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_taxdocument',
                'ordering': ['-tax_year', '-generated_at'],
                'indexes': [models.Index(fields=['consultant', 'tax_year'], name='payments_ta_consult_05b880_idx'), models.Index(fields=['tax_year', 'generated_at'], name='payments_ta_tax_yea_22a41f_idx'), models.Index(fields=['filed_with_irs', 'tax_year'], name='payments_ta_filed_w_728ba0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='taxdocument',
            constraint=models.UniqueConstraint(fields=('consultant', 'tax_year', 'document_type'), name='unique_consultant_tax_year_type'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_c4e513_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['external_reference'], name='payments_pa_externa_e4a306_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['confirmed_at'], name='payments_pa_confirm_41af8d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreconciliation',
            index=models.Index(fields=['batch'], name='payments_pa_batch_i_745609_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreconciliation',
            index=models.Index(fields=['status', 'reconciliation_date'], name='payments_pa_status_e6c0ab_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreconciliation',
            index=models.Index(fields=['reconciled_by', 'reconciliation_date'], name='payments_pa_reconci_188cff_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['consultant', 'status'], name='payments_pa_consult_bb928b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['consultant', 'is_default'], name='payments_pa_consult_ef8a5f_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(fields=('consultant', 'account_number'), name='unique_consultant_account'),
        ),
        migrations.AddIndex(
            model_name='paymentauditlog',
            index=models.Index(fields=['target_model', 'target_id', 'timestamp'], name='payments_pa_target__d78ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentauditlog',
            index=models.Index(fields=['actor', 'timestamp'], name='payments_pa_actor_i_49f5ea_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentauditlog',
            index=models.Index(fields=['action_type', 'timestamp'], name='payments_pa_action__6ecdeb_idx'),
        ),
    ]
