# Generated by Django 4.2.27 on 2026-01-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('consultant', 'Consultant'), ('manager', 'Manager'), ('finance', 'Finance'), ('director', 'Director'), ('admin', 'Admin')], default='consultant', help_text='User role for access control', max_length=20),
        ),
    ]
