# Generated by Django 4.2.27 on 2026-01-20 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('window', models.CharField(choices=[('DAILY', 'Daily'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global'), ('MANAGER', 'Manager'), ('CONSULTANT', 'Consultant')], max_length=15)),
                ('total_count', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approved_count', models.IntegerField(default=0)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_count', models.IntegerField(default=0)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rejected_count', models.IntegerField(default=0)),
                ('rejected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(choices=[('COMMISSION_DETAIL', 'Commission Detail'), ('PAYOUT_HISTORY', 'Payout History'), ('TAX_SUMMARY', 'Tax Summary'), ('RECONCILIATION', 'Reconciliation'), ('TEAM_PERFORMANCE', 'Team Performance'), ('MY_EARNINGS', 'My Earnings')], max_length=20)),
                ('export_format', models.CharField(choices=[('CSV', 'CSV'), ('PDF', 'PDF')], max_length=5)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('row_count', models.IntegerField(default=0)),
                ('file_size_bytes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayoutSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('window', models.CharField(choices=[('DAILY', 'Daily'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global'), ('MANAGER', 'Manager'), ('CONSULTANT', 'Consultant')], max_length=15)),
                ('batch_count', models.IntegerField(default=0)),
                ('payout_count', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('failed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_cycle_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Payout Summaries',
            },
        ),
        migrations.CreateModel(
            name='TaxSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('window', models.CharField(choices=[('DAILY', 'Daily'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], max_length=10)),
                ('tax_year', models.IntegerField()),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global'), ('MANAGER', 'Manager'), ('CONSULTANT', 'Consultant')], max_length=15)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('consultant_count', models.IntegerField(default=0)),
                ('above_threshold_count', models.IntegerField(default=0)),
                ('w9_approved_count', models.IntegerField(default=0)),
                ('w9_pending_count', models.IntegerField(default=0)),
                ('forms_generated_count', models.IntegerField(default=0)),
                ('forms_filed_count', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('scope_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tax Summaries',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('window', models.CharField(choices=[('DAILY', 'Daily'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_batches', models.IntegerField(default=0)),
                ('matched_count', models.IntegerField(default=0)),
                ('pending_count', models.IntegerField(default=0)),
                ('discrepancy_count', models.IntegerField(default=0)),
                ('total_expected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_discrepancy', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Reconciliation Summaries',
                'indexes': [models.Index(fields=['window', 'period_start'], name='idx_rs_period')],
            },
        ),
        migrations.AddConstraint(
            model_name='reconciliationsummary',
            constraint=models.UniqueConstraint(fields=('window', 'period_start'), name='unique_reconciliation_summary'),
        ),
        migrations.AddField(
            model_name='payoutsummary',
            name='scope_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exportlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissionmetric',
            name='scope_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='taxsummary',
            index=models.Index(fields=['window', 'tax_year', 'scope', 'scope_id'], name='idx_ts_lookup'),
        ),
        migrations.AddIndex(
            model_name='taxsummary',
            index=models.Index(fields=['tax_year', 'quarter'], name='idx_ts_year'),
        ),
        migrations.AddConstraint(
            model_name='taxsummary',
            constraint=models.UniqueConstraint(fields=('window', 'tax_year', 'quarter', 'scope', 'scope_id'), name='unique_tax_summary'),
        ),
        migrations.AddConstraint(
            model_name='taxsummary',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('scope', 'GLOBAL'), ('scope_id__isnull', True)), models.Q(('scope', 'CONSULTANT'), ('scope_id__isnull', False)), _connector='OR'), name='tax_summary_scope_check'),
        ),
        migrations.AddIndex(
            model_name='payoutsummary',
            index=models.Index(fields=['window', 'scope', 'scope_id', 'period_start'], name='idx_ps_lookup'),
        ),
        migrations.AddIndex(
            model_name='payoutsummary',
            index=models.Index(fields=['period_start', 'period_end'], name='idx_ps_period'),
        ),
        migrations.AddConstraint(
            model_name='payoutsummary',
            constraint=models.UniqueConstraint(fields=('window', 'period_start', 'scope', 'scope_id'), name='unique_payout_summary'),
        ),
        migrations.AddConstraint(
            model_name='payoutsummary',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('scope', 'GLOBAL'), ('scope_id__isnull', True)), models.Q(('scope__in', ['MANAGER', 'CONSULTANT']), ('scope_id__isnull', False)), _connector='OR'), name='payout_summary_scope_check'),
        ),
        migrations.AddIndex(
            model_name='exportlog',
            index=models.Index(fields=['user', 'created_at'], name='idx_el_user'),
        ),
        migrations.AddIndex(
            model_name='exportlog',
            index=models.Index(fields=['report_type', 'created_at'], name='idx_el_type'),
        ),
        migrations.AddIndex(
            model_name='commissionmetric',
            index=models.Index(fields=['window', 'scope', 'scope_id', 'period_start'], name='idx_cm_lookup'),
        ),
        migrations.AddIndex(
            model_name='commissionmetric',
            index=models.Index(fields=['period_start', 'period_end'], name='idx_cm_period'),
        ),
        migrations.AddConstraint(
            model_name='commissionmetric',
            constraint=models.UniqueConstraint(fields=('window', 'period_start', 'scope', 'scope_id'), name='unique_commission_metric'),
        ),
        migrations.AddConstraint(
            model_name='commissionmetric',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('scope', 'GLOBAL'), ('scope_id__isnull', True)), models.Q(('scope__in', ['MANAGER', 'CONSULTANT']), ('scope_id__isnull', False)), _connector='OR'), name='commission_metric_scope_check'),
        ),
    ]
