# Generated by Django 4.2.27 on 2026-01-19 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('base', 'Base Commission'), ('override', 'Manager Override'), ('adjustment', 'Adjustment')], db_index=True, help_text='Type of commission', max_length=20)),
                ('transaction_date', models.DateField(help_text='When the sale/transaction occurred')),
                ('sale_amount', models.DecimalField(decimal_places=2, help_text='Sale value excluding GST', max_digits=12)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, help_text='GST percentage at transaction time (e.g., 10.00)', max_digits=5)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Commission percentage applied (e.g., 7.00 for 7%)', max_digits=5)),
                ('calculated_amount', models.DecimalField(decimal_places=2, help_text='Final commission amount (immutable once approved)', max_digits=12)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], db_index=True, default='draft', help_text='Current state in lifecycle', max_length=20)),
                ('reference_number', models.CharField(help_text='External transaction reference (e.g., invoice number)', max_length=50, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or context')),
                ('override_level', models.IntegerField(blank=True, help_text='For overrides: 1=direct manager, 2=senior manager, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When approved', null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment was processed', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if state=rejected)')),
                ('adjustment_for', models.ForeignKey(blank=True, help_text='For adjustments: original commission being corrected', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='commissions.commission')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved this commission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions_approved', to=settings.AUTH_USER_MODEL)),
                ('consultant', models.ForeignKey(help_text='User who earned this commission', on_delete=django.db.models.deletion.PROTECT, related_name='commissions_earned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='Who created this commission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions_created', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, help_text='For overrides: manager at time of transaction (denormalized for immutability)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='override_commissions', to=settings.AUTH_USER_MODEL)),
                ('parent_commission', models.ForeignKey(blank=True, help_text='For overrides: links to base commission', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_commissions', to='commissions.commission')),
            ],
            options={
                'db_table': 'commissions_commission',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_role', models.CharField(choices=[('MANAGER', 'Manager'), ('ADMIN', 'Admin/Director')], default='MANAGER', help_text='Required role level for this approval', max_length=20)),
                ('is_auto_approved', models.BooleanField(default=False, help_text='Whether this was approved by a system rule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_approver', models.ForeignKey(blank=True, help_text='The user specialized for this approval step (manager/admin)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_approvals', to=settings.AUTH_USER_MODEL)),
                ('commission', models.OneToOneField(help_text='The commission this approval workflow belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='commissions.commission')),
            ],
            options={
                'verbose_name': 'Commission Approval',
                'verbose_name_plural': 'Commission Approvals',
                'db_table': 'commissions_approval',
            },
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMIT', 'Submitted'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('PAID', 'Marked as Paid')], help_text='The action taken (Submit, Approve, Reject, Paid)', max_length=20)),
                ('from_state', models.CharField(help_text='State before action', max_length=20)),
                ('to_state', models.CharField(help_text='State after action', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes or rejection reasons')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text='The user who performed the action', on_delete=django.db.models.deletion.PROTECT, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('approval_record', models.ForeignKey(help_text='The parent approval workflow record', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='commissions.commissionapproval')),
            ],
            options={
                'verbose_name': 'Approval History',
                'verbose_name_plural': 'Approval Histories',
                'db_table': 'commissions_approval_history',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['consultant', 'state'], name='commissions_consult_9b3371_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['manager', 'state', 'commission_type'], name='commissions_manager_a7abb6_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['transaction_date', 'state'], name='commissions_transac_7504b7_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['state', 'created_at'], name='commissions_state_bb3427_idx'),
        ),
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('commission_type', 'base'), ('manager__isnull', True)), models.Q(('commission_type', 'base'), _negated=True), _connector='OR'), name='base_no_manager'),
        ),
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('commission_type', 'override'), ('manager__isnull', False)), models.Q(('commission_type', 'override'), _negated=True), _connector='OR'), name='override_has_manager'),
        ),
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('adjustment_for__isnull', False), ('commission_type', 'adjustment')), models.Q(('commission_type', 'adjustment'), _negated=True), _connector='OR'), name='adjustment_has_reference'),
        ),
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.CheckConstraint(check=models.Q(('consultant', models.F('approved_by')), _negated=True), name='cannot_approve_own'),
        ),
    ]
