# Generated by Django 4.2.27 on 2026-01-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='client_name',
            field=models.CharField(blank=True, help_text='Name of the client/customer', max_length=255),
        ),
    ]
