# Generated by Django 4.2.27 on 2026-01-20 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(choices=[('PAY_001', 'Payment Completed'), ('PAY_002', 'Payment Failed'), ('PAY_003', 'Payment Retried'), ('COMP_001', 'W-9 Missing'), ('COMP_002', 'W-9 Rejected'), ('COMP_003', '1099 Generated'), ('COMP_004', '1099 Ready for Filing'), ('OUT_001', 'Payout Released'), ('OUT_002', 'Payout Delayed'), ('ANLT_001', 'KPI Threshold Breach'), ('ANLT_002', 'Reconciliation Discrepancy'), ('SYS_001', 'Aggregation Job Failed'), ('SYS_002', 'Export Ready')], max_length=20)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'In-App')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced')], default='PENDING', max_length=10)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=10)),
                ('source_model', models.CharField(blank=True, max_length=50)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PAY_001', 'Payment Completed'), ('PAY_002', 'Payment Failed'), ('PAY_003', 'Payment Retried'), ('COMP_001', 'W-9 Missing'), ('COMP_002', 'W-9 Rejected'), ('COMP_003', '1099 Generated'), ('COMP_004', '1099 Ready for Filing'), ('OUT_001', 'Payout Released'), ('OUT_002', 'Payout Delayed'), ('ANLT_001', 'KPI Threshold Breach'), ('ANLT_002', 'Reconciliation Discrepancy'), ('SYS_001', 'Aggregation Job Failed'), ('SYS_002', 'Export Ready')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read'), ('ARCHIVED', 'Archived')], default='UNREAD', max_length=10)),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('notification_log', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inbox_entry', to='notifications.notificationlog')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_inbox', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification Inbox Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(choices=[('PAY_001', 'Payment Completed'), ('PAY_002', 'Payment Failed'), ('PAY_003', 'Payment Retried'), ('COMP_001', 'W-9 Missing'), ('COMP_002', 'W-9 Rejected'), ('COMP_003', '1099 Generated'), ('COMP_004', '1099 Ready for Filing'), ('OUT_001', 'Payout Released'), ('OUT_002', 'Payout Delayed'), ('ANLT_001', 'KPI Threshold Breach'), ('ANLT_002', 'Reconciliation Discrepancy'), ('SYS_001', 'Aggregation Job Failed'), ('SYS_002', 'Export Ready')], max_length=20)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'In-App')], max_length=10)),
                ('scheduled_for', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_for'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='idx_scheduled_queue'), models.Index(fields=['recipient', 'event_type'], name='idx_scheduled_recip_event')],
            },
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['recipient', 'created_at'], name='idx_notif_recipient_created'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['event_type', 'created_at'], name='idx_notif_event_created'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status', 'channel'], name='idx_notif_status_channel'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status', 'next_retry_at'], name='idx_notif_retry_queue'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['source_model', 'source_id'], name='idx_notif_source'),
        ),
        migrations.AddIndex(
            model_name='notificationinbox',
            index=models.Index(fields=['recipient', 'status'], name='idx_inbox_recipient_status'),
        ),
        migrations.AddIndex(
            model_name='notificationinbox',
            index=models.Index(fields=['recipient', 'created_at'], name='idx_inbox_recipient_created'),
        ),
    ]
