# Generated by Django 4.2.27 on 2026-01-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationinbox',
            name='event_type',
            field=models.CharField(choices=[('PAY_001', 'Payment Completed'), ('PAY_002', 'Payment Failed'), ('PAY_003', 'Payment Retried'), ('COMP_001', 'W-9 Missing'), ('COMP_002', 'W-9 Rejected'), ('COMP_003', '1099 Generated'), ('COMP_004', '1099 Ready for Filing'), ('OUT_001', 'Payout Released'), ('OUT_002', 'Payout Delayed'), ('ANLT_001', 'KPI Threshold Breach'), ('ANLT_002', 'Reconciliation Discrepancy'), ('SYS_001', 'Aggregation Job Failed'), ('SYS_002', 'Export Ready'), ('COMM_001', 'Commission Submitted'), ('COMM_002', 'Commission Approved'), ('COMM_003', 'Commission Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('PAY_001', 'Payment Completed'), ('PAY_002', 'Payment Failed'), ('PAY_003', 'Payment Retried'), ('COMP_001', 'W-9 Missing'), ('COMP_002', 'W-9 Rejected'), ('COMP_003', '1099 Generated'), ('COMP_004', '1099 Ready for Filing'), ('OUT_001', 'Payout Released'), ('OUT_002', 'Payout Delayed'), ('ANLT_001', 'KPI Threshold Breach'), ('ANLT_002', 'Reconciliation Discrepancy'), ('SYS_001', 'Aggregation Job Failed'), ('SYS_002', 'Export Ready'), ('COMM_001', 'Commission Submitted'), ('COMM_002', 'Commission Approved'), ('COMM_003', 'Commission Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='schedulednotification',
            name='event_type',
            field=models.CharField(choices=[('PAY_001', 'Payment Completed'), ('PAY_002', 'Payment Failed'), ('PAY_003', 'Payment Retried'), ('COMP_001', 'W-9 Missing'), ('COMP_002', 'W-9 Rejected'), ('COMP_003', '1099 Generated'), ('COMP_004', '1099 Ready for Filing'), ('OUT_001', 'Payout Released'), ('OUT_002', 'Payout Delayed'), ('ANLT_001', 'KPI Threshold Breach'), ('ANLT_002', 'Reconciliation Discrepancy'), ('SYS_001', 'Aggregation Job Failed'), ('SYS_002', 'Export Ready'), ('COMM_001', 'Commission Submitted'), ('COMM_002', 'Commission Approved'), ('COMM_003', 'Commission Rejected')], max_length=20),
        ),
    ]
